// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Order struct {
	ID          int    `json:"id"`
	ProductName string `json:"productName"`
	Quantity    int    `json:"quantity"`
	CreatedAt   string `json:"createdAt"`
}

type Query struct {
}
